# Generated by Django 5.1.3 on 2024-11-26 18:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
